language: java

dist: trusty
sudo: required

jdk:
  - oraclejdk8

notifications:
  slack: cloudfoundry:xvgjKLNQTyqAFMnsTywVHik9

install:
  - wget http://www-us.apache.org/dist/lucene/solr/6.4.1/solr-6.4.1.tgz
  - tar -xvf solr-6.4.1.tgz
  - ./solr-6.4.1/bin/solr start
  - ./solr-6.4.1/bin/solr create -c solr
  - sudo apt-get update -y --fix-missing
  - sudo apt-get purge maven maven2 -y
  - sudo apt-get purge maven3 -y
  - sudo apt-add-repository ppa:andrei-pozolotin/maven3 -y
  - sudo apt-get update -y
  - sudo apt-get install maven3 -y
  - mvn -version

script:
  - mvn -pl '!spring-eg-content-solr' -pl '!spring-eg-content-solr-boot-starter' test
  - mvn -pl spring-eg-content-solr -pl spring-eg-content-commons test
  - unset SOLR_PASSWORD
  - unset SOLR_USERNAME
  - export SOLR_URL=$INSECURE_SOLR
  - mvn -pl spring-eg-content-solr -pl spring-eg-content-commons test
  - unset SOLR_URL
  - mvn -pl spring-eg-content-solr-boot-starter test



